name: oop_boolean_networks_rna_mirna
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - black
  - flake8
  - isort
  - networkx
  - matplotlib
  - pip:
    - python-dotenv
    - mkdocs
    - networkx
    - matplotlib
    - -e .